spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/price_alerts
    username: alerts
    password: alerts
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: tom.burrows.commons.events
        spring.json.value.default.type: tom.burrows.commons.events.AlertTriggeredEvent
        spring.json.use.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health
