spring:
  application:
    name: price-ingestion-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: -1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

ingestion:
  poll-interval: 45s
  currency: usd
  base-url: https://api.coingecko.com/api/v3
  symbols:
    - coin-id: bitcoin
      symbol: BTC
    - coin-id: ethereum
      symbol: ETH
    - coin-id: solana
      symbol: SOL
